# Generated by Django 4.1 on 2022-08-08 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0002_products_delete_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Producto',
        ),
    ]
